
server.port=9090
spring.application.name=config-server
management.endpoints.web.exposure.include=*

payment.name = GitServer

spring.datasource.username=sa
spring.datasource.password=Quest
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
