
server.port=8888
spring.application.name=config-server
management.endpoints.web.exposure.include=*

spring.datasource.username=sa
spring.datasource.password=Quest
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
